/* generated by roblox2web 1.0.0 */
window.GAME_DATA = {
 "meta": {
  "gameName": "Pet Collector Simulator",
  "projectName": "PetCollectorSimulator",
  "generator": "roblox2web 1.0.0",
  "genre": "pet-simulator",
  "sourceKind": "rojo",
  "links": [
   {
    "title": "Исходники (GitHub)",
    "url": "https://github.com/JoLiKs/pet-collector-sim"
   },
   {
    "title": "Конвертер roblox2web",
    "url": "https://github.com/JoLiKs/roblox2web"
   }
  ]
 },
 "config": {
  "PRODUCTS": {
   "GEMS_SMALL": {
    "Kind": "Gems",
    "Amount": 100,
    "Name": "Pile of Gems",
    "SuggestedPrice": 79
   },
   "GEMS_MEDIUM": {
    "Kind": "Gems",
    "Amount": 550,
    "Name": "Bag of Gems",
    "SuggestedPrice": 349
   },
   "GEMS_LARGE": {
    "Kind": "Gems",
    "Amount": 1500,
    "Name": "Chest of Gems",
    "SuggestedPrice": 899
   },
   "COINS_SMALL": {
    "Kind": "Coins",
    "Clicks": 1500,
    "Min": 2000,
    "Name": "Coin Pouch",
    "SuggestedPrice": 79
   },
   "COINS_LARGE": {
    "Kind": "Coins",
    "Clicks": 15000,
    "Min": 25000,
    "Name": "Coin Vault",
    "SuggestedPrice": 399
   },
   "LUCK_2X_15M": {
    "Kind": "Luck",
    "Boost": "Luck2",
    "Multiplier": 2,
    "Seconds": 900,
    "Name": "Lucky Clover x2 (15m)",
    "SuggestedPrice": 79
   },
   "LUCK_5X_10M": {
    "Kind": "Luck",
    "Boost": "Luck5",
    "Multiplier": 5,
    "Seconds": 600,
    "Name": "Super Clover x5 (10m)",
    "SuggestedPrice": 199
   }
  },
  "GAMEPASSES": {
   "DOUBLE_COINS": {
    "Name": "2x Coins",
    "Description": "Double ALL coins you collect. Forever!",
    "SuggestedPrice": 299
   },
   "DOUBLE_SPEED": {
    "Name": "2x Speed",
    "Description": "Run twice as fast across every world.",
    "SuggestedPrice": 149
   },
   "AUTO_COLLECT": {
    "Name": "Auto Collect",
    "Description": "Coins are collected for you automatically, even while you explore.",
    "SuggestedPrice": 399
   },
   "VIP": {
    "Name": "VIP",
    "Description": "+25% coins, +1 pet slot, [VIP] tag, double daily rewards.",
    "SuggestedPrice": 599
   }
  },
  "GAMEPASS_ORDER": [
   "DOUBLE_COINS",
   "AUTO_COLLECT",
   "VIP",
   "DOUBLE_SPEED"
  ],
  "PRODUCT_ORDER": [
   "GEMS_SMALL",
   "GEMS_MEDIUM",
   "GEMS_LARGE",
   "COINS_SMALL",
   "COINS_LARGE",
   "LUCK_2X_15M",
   "LUCK_5X_10M"
  ],
  "PASS_EFFECTS": {
   "COIN_MULT_DOUBLE": 2,
   "SPEED_MULT_DOUBLE": 2,
   "VIP_COIN_BONUS": 0.25,
   "VIP_EXTRA_SLOTS": 1,
   "VIP_LUCK_BONUS": 0.1,
   "VIP_DAILY_MULT": 2,
   "PREMIUM_COIN_BONUS": 0.1,
   "PREMIUM_DAILY_GEMS": 5,
   "AUTO_CLICKS_PER_SECOND": 2
  },
  "STUDIO_GRANT_ALL_PASSES": false,
  "AUTOSAVE_INTERVAL": 60,
  "SESSION_LOCK_TIMEOUT": 180,
  "LOAD_ATTEMPTS": 8,
  "LOAD_LOCK_RETRY_DELAY": 4,
  "SAVE_ATTEMPTS": 5,
  "STUDIO_FALLBACK_TO_EPHEMERAL": true,
  "GAME_NAME": "Pet Collector Simulator",
  "MAX_CLICKS_PER_SECOND": 12,
  "CLICK_BURST": 6,
  "BASE_PET_SLOTS": 3,
  "BASE_BAG_SIZE": 30,
  "BASE_WALKSPEED": 16,
  "MAX_WALKSPEED": 56,
  "JUMP_POWER": 50,
  "GOLD_CHANCE": 0.02,
  "GOLD_POWER_MULT": 2,
  "SELL_VALUE_PER_POWER": 40,
  "MAX_COINS": 1000000000000000,
  "MAX_GEMS": 1000000000,
  "EGG_MAX_DISTANCE": 45,
  "HATCH_COUNTS": [
   1,
   3
  ],
  "REBIRTH_BASE_COST": 50000,
  "REBIRTH_COST_GROWTH": 4,
  "REBIRTH_MULT_PER": 0.5,
  "REBIRTH_GEMS_BASE": 20,
  "REBIRTH_GEMS_PER": 5,
  "DAILY_REWARDS": [
   {
    "Gems": 10,
    "Clicks": 300
   },
   {
    "Gems": 15,
    "Clicks": 500
   },
   {
    "Gems": 20,
    "Clicks": 800
   },
   {
    "Gems": 25,
    "Clicks": 1200,
    "Luck2Minutes": 10
   },
   {
    "Gems": 35,
    "Clicks": 2000
   },
   {
    "Gems": 50,
    "Clicks": 3000,
    "Luck2Minutes": 15
   },
   {
    "Gems": 120,
    "Clicks": 6000,
    "Luck2Minutes": 30
   }
  ],
  "ANTICHEAT": {
   "STRIKE_WINDOW": 60,
   "STRIKE_KICK_THRESHOLD": 60,
   "MAX_HORIZONTAL_SPEED": 220,
   "TELEPORT_GRACE": 2.5
  }
 },
 "rarities": {
  "Common": {
   "Order": 1,
   "Color": "#bebec8",
   "Scale": 1
  },
  "Uncommon": {
   "Order": 2,
   "Color": "#5ad26e",
   "Scale": 1.08
  },
  "Rare": {
   "Order": 3,
   "Color": "#4696ff",
   "Scale": 1.16
  },
  "Epic": {
   "Order": 4,
   "Color": "#b45aff",
   "Scale": 1.26
  },
  "Legendary": {
   "Order": 5,
   "Color": "#ffaa28",
   "Scale": 1.38
  },
  "Mythic": {
   "Order": 6,
   "Color": "#ff4678",
   "Scale": 1.5
  }
 },
 "luckMinOrder": 3,
 "pets": [
  {
   "Id": "bunbun",
   "Name": "Bunbun",
   "Rarity": "Common",
   "Power": 1,
   "Look": {
    "Body": "#faf0e1",
    "Accent": "#ffaab9",
    "Shape": "Round",
    "Ears": "Long",
    "Extras": [
     "Tail"
    ]
   }
  },
  {
   "Id": "chirpy",
   "Name": "Chirpy",
   "Rarity": "Common",
   "Power": 1.5,
   "Look": {
    "Body": "#ffe25a",
    "Accent": "#ff9632",
    "Shape": "Round",
    "Ears": "None",
    "Extras": [
     "Beak",
     "Wings"
    ]
   }
  },
  {
   "Id": "mossy",
   "Name": "Mossy Frog",
   "Rarity": "Uncommon",
   "Power": 3,
   "Look": {
    "Body": "#6ec85a",
    "Accent": "#3c8c3c",
    "Shape": "Wide",
    "Ears": "Round",
    "Extras": []
   }
  },
  {
   "Id": "bumblet",
   "Name": "Bumblet",
   "Rarity": "Rare",
   "Power": 8,
   "Look": {
    "Body": "#ffcd32",
    "Accent": "#282828",
    "Shape": "Round",
    "Ears": "None",
    "Extras": [
     "Wings",
     "Antenna"
    ]
   }
  },
  {
   "Id": "sunfox",
   "Name": "Sunny Fox",
   "Rarity": "Epic",
   "Power": 25,
   "Look": {
    "Body": "#ff8c32",
    "Accent": "#fff5e1",
    "Shape": "Tall",
    "Ears": "Pointy",
    "Extras": [
     "Tail"
    ]
   }
  },
  {
   "Id": "dandy",
   "Name": "Dandy King",
   "Rarity": "Legendary",
   "Power": 90,
   "Look": {
    "Body": "#ffbe3c",
    "Accent": "#ff781e",
    "Shape": "Round",
    "Ears": "Round",
    "Extras": [
     "Crown",
     "Tail"
    ]
   }
  },
  {
   "Id": "acorny",
   "Name": "Acorny",
   "Rarity": "Common",
   "Power": 4,
   "Look": {
    "Body": "#b07846",
    "Accent": "#6e4628",
    "Shape": "Round",
    "Ears": "None",
    "Extras": [
     "Leaf"
    ]
   }
  },
  {
   "Id": "pinecub",
   "Name": "Pinecub",
   "Rarity": "Common",
   "Power": 6,
   "Look": {
    "Body": "#8c5f3c",
    "Accent": "#dcbe96",
    "Shape": "Wide",
    "Ears": "Round",
    "Extras": [
     "Tail"
    ]
   }
  },
  {
   "Id": "owlet",
   "Name": "Owlet",
   "Rarity": "Uncommon",
   "Power": 14,
   "Look": {
    "Body": "#a08264",
    "Accent": "#ffebc8",
    "Shape": "Tall",
    "Ears": "Pointy",
    "Extras": [
     "Beak",
     "Wings"
    ]
   }
  },
  {
   "Id": "mushling",
   "Name": "Mushling",
   "Rarity": "Rare",
   "Power": 36,
   "Look": {
    "Body": "#f0e6d7",
    "Accent": "#e64646",
    "Shape": "Round",
    "Ears": "None",
    "Extras": [
     "Leaf"
    ]
   }
  },
  {
   "Id": "deerling",
   "Name": "Deerling",
   "Rarity": "Epic",
   "Power": 110,
   "Look": {
    "Body": "#c89664",
    "Accent": "#fff0dc",
    "Shape": "Tall",
    "Ears": "Long",
    "Extras": [
     "Horn",
     "Tail"
    ]
   }
  },
  {
   "Id": "elderwood",
   "Name": "Elderwood",
   "Rarity": "Legendary",
   "Power": 400,
   "Look": {
    "Body": "#785537",
    "Accent": "#46be5a",
    "Shape": "Tall",
    "Ears": "None",
    "Extras": [
     "Leaf",
     "Crown"
    ]
   }
  },
  {
   "Id": "gecko",
   "Name": "Dune Gecko",
   "Rarity": "Common",
   "Power": 18,
   "Look": {
    "Body": "#c8be64",
    "Accent": "#96823c",
    "Shape": "Wide",
    "Ears": "None",
    "Extras": [
     "Tail"
    ]
   }
  },
  {
   "Id": "scarab",
   "Name": "Sandy Scarab",
   "Rarity": "Common",
   "Power": 26,
   "Look": {
    "Body": "#3c82a0",
    "Accent": "#f0c850",
    "Shape": "Wide",
    "Ears": "None",
    "Extras": [
     "Antenna",
     "Wings"
    ]
   }
  },
  {
   "Id": "cactling",
   "Name": "Cactling",
   "Rarity": "Uncommon",
   "Power": 60,
   "Look": {
    "Body": "#50aa5a",
    "Accent": "#ff78aa",
    "Shape": "Tall",
    "Ears": "None",
    "Extras": [
     "Leaf"
    ]
   }
  },
  {
   "Id": "mirage",
   "Name": "Mirage Cat",
   "Rarity": "Rare",
   "Power": 150,
   "Look": {
    "Body": "#ebcd96",
    "Accent": "#7850a0",
    "Shape": "Round",
    "Ears": "Pointy",
    "Extras": [
     "Tail"
    ]
   }
  },
  {
   "Id": "serpent",
   "Name": "Sun Serpent",
   "Rarity": "Epic",
   "Power": 450,
   "Look": {
    "Body": "#ffbe46",
    "Accent": "#dc5028",
    "Shape": "Wide",
    "Ears": "None",
    "Extras": [
     "Flame",
     "Tail"
    ]
   }
  },
  {
   "Id": "sphinx",
   "Name": "Golden Sphinx",
   "Rarity": "Legendary",
   "Power": 1600,
   "Look": {
    "Body": "#ffd75a",
    "Accent": "#3c5ac8",
    "Shape": "Wide",
    "Ears": "Round",
    "Extras": [
     "Crown",
     "Wings"
    ]
   }
  },
  {
   "Id": "snowpup",
   "Name": "Snowy Pup",
   "Rarity": "Common",
   "Power": 80,
   "Look": {
    "Body": "#f5faff",
    "Accent": "#96c8f0",
    "Shape": "Round",
    "Ears": "Round",
    "Extras": [
     "Tail"
    ]
   }
  },
  {
   "Id": "penguin",
   "Name": "Icicle Penguin",
   "Rarity": "Common",
   "Power": 110,
   "Look": {
    "Body": "#323c50",
    "Accent": "#fff5eb",
    "Shape": "Tall",
    "Ears": "None",
    "Extras": [
     "Beak",
     "Fins"
    ]
   }
  },
  {
   "Id": "yeti",
   "Name": "Yeti Cub",
   "Rarity": "Uncommon",
   "Power": 260,
   "Look": {
    "Body": "#e1f0fa",
    "Accent": "#78aadc",
    "Shape": "Wide",
    "Ears": "Round",
    "Extras": [
     "Horn"
    ]
   }
  },
  {
   "Id": "aurora",
   "Name": "Aurora Fox",
   "Rarity": "Rare",
   "Power": 650,
   "Look": {
    "Body": "#a0e6dc",
    "Accent": "#be78ff",
    "Shape": "Tall",
    "Ears": "Pointy",
    "Extras": [
     "Tail",
     "Halo"
    ]
   }
  },
  {
   "Id": "stag",
   "Name": "Crystal Stag",
   "Rarity": "Epic",
   "Power": 1900,
   "Look": {
    "Body": "#96d2ff",
    "Accent": "#ffffff",
    "Shape": "Tall",
    "Ears": "Long",
    "Extras": [
     "Horn",
     "Halo"
    ]
   }
  },
  {
   "Id": "blizzdrake",
   "Name": "Blizzard Drake",
   "Rarity": "Legendary",
   "Power": 7000,
   "Look": {
    "Body": "#78befa",
    "Accent": "#ffffff",
    "Shape": "Wide",
    "Ears": "Pointy",
    "Extras": [
     "Wings",
     "Horn",
     "Tail"
    ]
   }
  },
  {
   "Id": "embermouse",
   "Name": "Ember Mouse",
   "Rarity": "Common",
   "Power": 350,
   "Look": {
    "Body": "#ff8c5a",
    "Accent": "#5a281e",
    "Shape": "Round",
    "Ears": "Round",
    "Extras": [
     "Tail",
     "Flame"
    ]
   }
  },
  {
   "Id": "lavaslug",
   "Name": "Lava Slug",
   "Rarity": "Common",
   "Power": 480,
   "Look": {
    "Body": "#e65a28",
    "Accent": "#ffdc5a",
    "Shape": "Wide",
    "Ears": "None",
    "Extras": [
     "Antenna"
    ]
   }
  },
  {
   "Id": "magmashell",
   "Name": "Magma Turtle",
   "Rarity": "Uncommon",
   "Power": 1100,
   "Look": {
    "Body": "#5a4646",
    "Accent": "#ff7828",
    "Shape": "Wide",
    "Ears": "None",
    "Extras": [
     "Flame"
    ]
   }
  },
  {
   "Id": "cinderwolf",
   "Name": "Cinder Wolf",
   "Rarity": "Rare",
   "Power": 2800,
   "Look": {
    "Body": "#463c41",
    "Accent": "#ff641e",
    "Shape": "Tall",
    "Ears": "Pointy",
    "Extras": [
     "Tail",
     "Flame"
    ]
   }
  },
  {
   "Id": "phoenix",
   "Name": "Phoenix Chick",
   "Rarity": "Epic",
   "Power": 8500,
   "Look": {
    "Body": "#ff5a32",
    "Accent": "#ffdc50",
    "Shape": "Round",
    "Ears": "None",
    "Extras": [
     "Wings",
     "Flame",
     "Beak"
    ]
   }
  },
  {
   "Id": "infernodrake",
   "Name": "Inferno Drake",
   "Rarity": "Legendary",
   "Power": 30000,
   "Look": {
    "Body": "#b4281e",
    "Accent": "#ffaa28",
    "Shape": "Wide",
    "Ears": "Pointy",
    "Extras": [
     "Wings",
     "Horn",
     "Flame",
     "Tail"
    ]
   }
  },
  {
   "Id": "slime",
   "Name": "Sparkle Slime",
   "Rarity": "Rare",
   "Power": 220,
   "Look": {
    "Body": "#78e6f0",
    "Accent": "#ffffff",
    "Shape": "Wide",
    "Ears": "None",
    "Extras": [
     "Antenna"
    ]
   }
  },
  {
   "Id": "prismcat",
   "Name": "Prism Cat",
   "Rarity": "Epic",
   "Power": 1300,
   "Look": {
    "Body": "#fa96dc",
    "Accent": "#82dcff",
    "Shape": "Round",
    "Ears": "Pointy",
    "Extras": [
     "Tail",
     "Halo"
    ]
   }
  },
  {
   "Id": "starbunny",
   "Name": "Star Bunny",
   "Rarity": "Epic",
   "Power": 2000,
   "Look": {
    "Body": "#fff5a0",
    "Accent": "#ffbe3c",
    "Shape": "Round",
    "Ears": "Long",
    "Extras": [
     "Tail",
     "Crown"
    ]
   }
  },
  {
   "Id": "cosmicwhale",
   "Name": "Cosmic Whale",
   "Rarity": "Legendary",
   "Power": 13000,
   "Look": {
    "Body": "#3c46b4",
    "Accent": "#ffe678",
    "Shape": "Wide",
    "Ears": "None",
    "Extras": [
     "Fins",
     "Halo"
    ]
   }
  },
  {
   "Id": "nebuladrake",
   "Name": "Nebula Dragon",
   "Rarity": "Mythic",
   "Power": 70000,
   "Look": {
    "Body": "#6e32be",
    "Accent": "#ff78e6",
    "Shape": "Wide",
    "Ears": "Pointy",
    "Extras": [
     "Wings",
     "Horn",
     "Halo",
     "Tail",
     "Crown"
    ]
   }
  }
 ],
 "eggs": [
  {
   "Id": "MeadowEgg",
   "Name": "Meadow Egg",
   "Zone": "Meadow",
   "Currency": "Coins",
   "Price": 150,
   "Color": "#fff5d7",
   "Pattern": "#78c864",
   "Pets": [
    {
     "Id": "bunbun",
     "Weight": 40
    },
    {
     "Id": "chirpy",
     "Weight": 30
    },
    {
     "Id": "mossy",
     "Weight": 18
    },
    {
     "Id": "bumblet",
     "Weight": 8
    },
    {
     "Id": "sunfox",
     "Weight": 3.5
    },
    {
     "Id": "dandy",
     "Weight": 0.5
    }
   ]
  },
  {
   "Id": "GemEgg",
   "Name": "Crystal Egg",
   "Zone": "Meadow",
   "Currency": "Gems",
   "Price": 75,
   "Color": "#8ce6ff",
   "Pattern": "#ffffff",
   "Pets": [
    {
     "Id": "slime",
     "Weight": 50
    },
    {
     "Id": "prismcat",
     "Weight": 28
    },
    {
     "Id": "starbunny",
     "Weight": 16.5
    },
    {
     "Id": "cosmicwhale",
     "Weight": 5
    },
    {
     "Id": "nebuladrake",
     "Weight": 0.5
    }
   ]
  },
  {
   "Id": "ForestEgg",
   "Name": "Forest Egg",
   "Zone": "Forest",
   "Currency": "Coins",
   "Price": 2500,
   "Color": "#96d28c",
   "Pattern": "#5a3c28",
   "Pets": [
    {
     "Id": "acorny",
     "Weight": 40
    },
    {
     "Id": "pinecub",
     "Weight": 30
    },
    {
     "Id": "owlet",
     "Weight": 18
    },
    {
     "Id": "mushling",
     "Weight": 8
    },
    {
     "Id": "deerling",
     "Weight": 3.5
    },
    {
     "Id": "elderwood",
     "Weight": 0.5
    }
   ]
  },
  {
   "Id": "DesertEgg",
   "Name": "Dune Egg",
   "Zone": "Desert",
   "Currency": "Coins",
   "Price": 60000,
   "Color": "#f5d78c",
   "Pattern": "#c8783c",
   "Pets": [
    {
     "Id": "gecko",
     "Weight": 40
    },
    {
     "Id": "scarab",
     "Weight": 30
    },
    {
     "Id": "cactling",
     "Weight": 18
    },
    {
     "Id": "mirage",
     "Weight": 8
    },
    {
     "Id": "serpent",
     "Weight": 3.5
    },
    {
     "Id": "sphinx",
     "Weight": 0.5
    }
   ]
  },
  {
   "Id": "FrostEgg",
   "Name": "Frost Egg",
   "Zone": "Frost",
   "Currency": "Coins",
   "Price": 1500000,
   "Color": "#c8ebff",
   "Pattern": "#64aaf0",
   "Pets": [
    {
     "Id": "snowpup",
     "Weight": 40
    },
    {
     "Id": "penguin",
     "Weight": 30
    },
    {
     "Id": "yeti",
     "Weight": 18
    },
    {
     "Id": "aurora",
     "Weight": 8
    },
    {
     "Id": "stag",
     "Weight": 3.5
    },
    {
     "Id": "blizzdrake",
     "Weight": 0.5
    }
   ]
  },
  {
   "Id": "VolcanoEgg",
   "Name": "Magma Egg",
   "Zone": "Volcano",
   "Currency": "Coins",
   "Price": 30000000,
   "Color": "#5a3c3c",
   "Pattern": "#ff7828",
   "Pets": [
    {
     "Id": "embermouse",
     "Weight": 40
    },
    {
     "Id": "lavaslug",
     "Weight": 30
    },
    {
     "Id": "magmashell",
     "Weight": 18
    },
    {
     "Id": "cinderwolf",
     "Weight": 8
    },
    {
     "Id": "phoenix",
     "Weight": 3.5
    },
    {
     "Id": "infernodrake",
     "Weight": 0.5
    }
   ]
  }
 ],
 "zones": [
  {
   "Id": "Meadow",
   "Name": "Sunny Meadow",
   "Multiplier": 1,
   "UnlockCost": 0,
   "RequiresRebirths": 0,
   "Floor": "#68be54",
   "Accent": "#ffd65a",
   "Sky": "#96cdff",
   "Decor": "Trees"
  },
  {
   "Id": "Forest",
   "Name": "Whispering Forest",
   "Multiplier": 3,
   "UnlockCost": 5000,
   "RequiresRebirths": 0,
   "Floor": "#3a8446",
   "Accent": "#8b5e3c",
   "Sky": "#78af96",
   "Decor": "Trees"
  },
  {
   "Id": "Desert",
   "Name": "Golden Dunes",
   "Multiplier": 9,
   "UnlockCost": 100000,
   "RequiresRebirths": 0,
   "Floor": "#e7c881",
   "Accent": "#56a050",
   "Sky": "#ffdca0",
   "Decor": "Cacti"
  },
  {
   "Id": "Frost",
   "Name": "Frostpeak Glade",
   "Multiplier": 27,
   "UnlockCost": 2500000,
   "RequiresRebirths": 0,
   "Floor": "#e2f0fc",
   "Accent": "#82c8ff",
   "Sky": "#bedcf5",
   "Decor": "Crystals"
  },
  {
   "Id": "Volcano",
   "Name": "Ember Caldera",
   "Multiplier": 81,
   "UnlockCost": 60000000,
   "RequiresRebirths": 1,
   "Floor": "#463a3a",
   "Accent": "#ff6e28",
   "Sky": "#78463c",
   "Decor": "Rocks"
  }
 ],
 "platformSize": 180,
 "upgrades": {
  "consts": {
   "CLICK_PER_LEVEL": 1,
   "SPEED_PER_LEVEL": 1.5,
   "LUCK_PER_LEVEL": 0.03,
   "BAG_PER_LEVEL": 10
  },
  "list": [
   {
    "Id": "Click",
    "Name": "Click Power",
    "Description": "+1 base coin per collect. (Resets on Rebirth)",
    "MaxLevel": 60,
    "Currency": "Coins",
    "BaseCost": 20,
    "Growth": 1.45,
    "Costs": null
   },
   {
    "Id": "Speed",
    "Name": "Swift Shoes",
    "Description": "+1.5 walk speed per level.",
    "MaxLevel": 8,
    "Currency": "Coins",
    "BaseCost": 500,
    "Growth": 2.2,
    "Costs": null
   },
   {
    "Id": "Luck",
    "Name": "Lucky Charm",
    "Description": "+3% hatch luck per level (better odds for rare pets).",
    "MaxLevel": 10,
    "Currency": "Coins",
    "BaseCost": 2000,
    "Growth": 2.1,
    "Costs": null
   },
   {
    "Id": "Bag",
    "Name": "Bigger Bag",
    "Description": "+10 pet storage per level.",
    "MaxLevel": 10,
    "Currency": "Coins",
    "BaseCost": 300,
    "Growth": 1.9,
    "Costs": null
   },
   {
    "Id": "Slots",
    "Name": "Pet Slot",
    "Description": "+1 equipped pet slot.",
    "MaxLevel": 4,
    "Currency": "Gems",
    "BaseCost": 0,
    "Growth": 1,
    "Costs": [
     100,
     300,
     800,
     2000
    ]
   }
  ]
 }
};
